# Generated by Django 5.1.2 on 2025-11-12 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteLeilao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('preco_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_leilao', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_ovinos/')),
                ('encerrado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ovino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_brinco', models.CharField(max_length=20, unique=True)),
                ('raca', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('cor', models.CharField(max_length=30)),
                ('peso_atual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidade_crias', models.IntegerField(blank=True, null=True)),
                ('peso_ao_nascer', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('filiacao', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Vendido', 'Vendido'), ('Reservado', 'Reservado')], default='Disponível', max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_ovinos/')),
            ],
        ),
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lances', to='ovinos.loteleilao')),
            ],
        ),
    ]
