# Generated by Django 5.1.2 on 2025-10-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ovino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_brinco', models.CharField(max_length=20, unique=True)),
                ('raca', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('cor', models.CharField(max_length=30)),
                ('peso_atual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidade_crias', models.IntegerField(blank=True, null=True)),
                ('peso_ao_nascer', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('filiacao', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Vendido', 'Vendido'), ('Reservado', 'Reservado')], default='Disponível', max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_ovinos/')),
            ],
        ),
    ]
