# Generated by Django 5.1.2 on 2025-11-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteleilao',
            name='encerrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loteleilao',
            name='numero_lote',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
