# Generated by Django 5.1.2 on 2025-10-18 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovinos', '0002_lance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteLeilao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField()),
                ('preco_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_leilao', models.DateField(default=django.utils.timezone.now)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_ovinos/')),
            ],
        ),
    ]
