# Generated by Django 5.1.2 on 2025-11-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovinos', '0004_alter_loteleilao_numero_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteleilao',
            name='numero_lote',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
